name: Deploy to Heroku

on:
  push:
    branches: [ "main" ]


jobs:
  heroku-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          branch: release
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "turn-track"
          heroku_email: "turn.track@protonmail.com"
          
      
